### PR TITLE
First working version

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1)

### CODE REVIEW

**Comment by aledj2** [comment]
+@aledj2 

---

Review status: 0 of 7 files reviewed, all discussions resolved (waiting on @aledj2)

---



*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-:-LFRZcY24AtzFOrQlXEN:bweg3f8)*

**Comment by aledj2** [comment]
Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed, 8 unresolved discussions (waiting on @andyb3 and @aledj2)

---

*[dxapp.json, line 6 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFRZmRRCFCwvWklWr_i:-LFRZmRSD6lD9WZxYEYq:b-v38wsv) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/dxapp.json#L6)):*
> ```JSON
>   "summary": "v1.0 Downsamples BAMs for Oxford Nanopore HTT repeat counting workflow",
>   "dxapi": "1.0.0",
>   "version": "1.0",
> ```

May be overkill now we include the version number in the app name but please add:
 "properties": {
    "github release": "v1.2"
  },

---

*[dxapp.json, line 43 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFR_3QXDcwZdInEalr6:-LFR_3QXDcwZdInEalr7:b-hrq5d4) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/dxapp.json#L43)):*
> ```JSON
>         "*.bam"
>       ],
>       "help": "Sorted BAM file"
> ```

downsampled sorted BAM

---

*[dxapp.json, line 71 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFR_CbXCtmRRxJKGt1e:-LFR_CbXCtmRRxJKGt1f:b-wkulcm) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/dxapp.json#L71)):*
> ```JSON
>     "file": "src/nanopore_htt_downsample.sh",
>     "systemRequirements": {
>       "*": {
> ```

haven't seen this before. I guess this is for all regions?

---

*[README.md, line 10 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFR_Y2XE7dARtIBOqI-:-LFR_Y2XE7dARtIBOqI0:bebcb9c) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/README.md#L10)):*
> ```
> proportiion
> ```
typo

---

*[README.md, line 10 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFR_he7CWviIABMB6L0:-LFR_he7CWviIABMB6L1:b-89vja6) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/README.md#L10)):*
> ```Markdown
> 
> ## What data are required for this app to run?
> The app requires a sorted BAM file containing Oxford Nanopore reads aligned to hg19 reference sequence. The BAM file must have previously been run through the DNAnexus Sambamba_Chanjo app using the bed file `Pan_XXXX` (HTT repeat region +-500bp). The desired read depth to downsample to must also be specified. This app uses the `*.sambamba_ouput.bed` output from the previous step to calculate the proportiion of reads that must be kept to achieve the desired read depth. 
> ```

Can you make the inputs clearer by putting into a list ?

---

*[src/nanopore_htt_downsample.sh, line 26 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFRaQO8E_j_LXKNeR41:-LFRaQO8E_j_LXKNeR42:bn2xmrk) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/src/nanopore_htt_downsample.sh#L26)):*
> ```Shell
> 	original_cov=$(grep 'chr4'$'\t''3076103'$'\t''3077166' ${sambambaoutput_path} | cut -f10)
> 
> 	# Calculate downsample factor
> ```

what is bc -l?

---

*[src/nanopore_htt_downsample.sh, line 33 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFRaaSQA2XQdD69V0pH:-LFRaaSQA2XQdD69V0pI:bh7axcy) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/src/nanopore_htt_downsample.sh#L33)):*
> ```Shell
> 	# be picked up from coverage report at QC)
> 
> 	if echo $downsample_factor | awk '{exit !( $1 > 1.0)}'; then
> ```

what is this awk command?

---

*[src/nanopore_htt_downsample.sh, line 50 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFRb1ViBpwCQfU7v7uf:-LFRb1ViBpwCQfU7v7ug:b-am94e8) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/src/nanopore_htt_downsample.sh#L50)):*
> ```Shell
> 	$HOME/out/downsampledbai/bam/${bam_prefix}.downsampled_${downsampleto}x.bam.bai
> 
> 	# Upload all results files and directories in $HOME/out/moka_picard_stats/
> ```

not this moka_picard_stats

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1)*

**Comment by aledj2** [comment]
Review status: 4 of 7 files reviewed, 9 unresolved discussions (waiting on @andyb3 and @aledj2)

---

*[dxapp.json, line 21 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFRcQOy7zbnAftw5JNR:-LFRcQOy7zbnAftw5JNS:b10m8lt) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/dxapp.json#L21)):*
> ```JSON
>       "label": "Sambamba coverage for BAM",
>       "class": "file",
>       "optional": false,
> ```

by default all inputs are not optional so no need to specify this (it's not specified for the other inputs)

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1)*

**Comment by andyb3** [comment]
Review status: 4 of 7 files reviewed, 9 unresolved discussions (waiting on @aledj2 and @andyb3)

---

*[dxapp.json, line 6 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFRZmRRCFCwvWklWr_i:-LFYv3PDA69UJFpjNKXS:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/dxapp.json#L6)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

May be overkill now we include the version number in the app name but please add:
 "properties": {
    "github release": "v1.2"
  },
</blockquote></details>

Done.

---

*[dxapp.json, line 21 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFRcQOy7zbnAftw5JNR:-LFYuugc7Nnx2DYjhsEC:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/dxapp.json#L21)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

by default all inputs are not optional so no need to specify this (it's not specified for the other inputs)
</blockquote></details>

Done.

---

*[dxapp.json, line 43 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFR_3QXDcwZdInEalr6:-LFZ0G2qDRh-O4kxSkbz:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/dxapp.json#L43)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

downsampled sorted BAM
</blockquote></details>

Done.

---

*[dxapp.json, line 71 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFR_CbXCtmRRxJKGt1e:-LFYutqi44QZ-uuBKfq_:b7txrij) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/dxapp.json#L71)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

haven't seen this before. I guess this is for all regions?
</blockquote></details>

I don't think this is regions. I think this is where you can specify different instance types for different entrypoints if you have parallelized apps, so i guess * means all entrypoints use this instance type, but looking at other apps we normally have 'main': {} here rather than '*': {} so have changed to this for consistency

---

*[README.md, line 10 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFR_he7CWviIABMB6L0:-LFYuhO14KELzXO9rg_W:b-200kz7) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/README.md#L10)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Can you make the inputs clearer by putting into a list ?
</blockquote></details>

Done. But just remembered I need to create a panel in Moka so I can fill the PanXXXX placeholder

---

*[README.md, line 10 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFR_Y2XE7dARtIBOqI-:-LFYut-T5ER5iouDhjZr:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/README.md#L10)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> proportiion
> ```
typo
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1)*

**Comment by aledj2** [comment]
Reviewed 1 of 3 files at r2.
Review status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @andyb3)

---

*[README.md, line 10 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFR_he7CWviIABMB6L0:-LFabDv38D-v3-qmNSeb:bpq9pja) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/README.md#L10)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Done. But just remembered I need to create a panel in Moka so I can fill the PanXXXX placeholder
</blockquote></details>

ok, will hold off on this

---

*[src/nanopore_htt_downsample.sh, line 35 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFabojH5Xt_FV9uXLOS:-LFabojH5Xt_FV9uXLOT:b-oxdpin) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/c113d88288ef4fbf8c61171485aab83c547ca509/src/nanopore_htt_downsample.sh#L35)):*
> ```
> If it is greater than 0,
> ```
 If it is greater than 1?

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1)*

**Comment by andyb3** [comment]
Review status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @aledj2)

---

*[src/nanopore_htt_downsample.sh, line 35 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFabojH5Xt_FV9uXLOS:-LFc50L571scgD1lIk5F:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/c113d88288ef4fbf8c61171485aab83c547ca509/src/nanopore_htt_downsample.sh#L35)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> If it is greater than 0,
> ```
 If it is greater than 1?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1)*

**Comment by andyb3** [comment]
Review status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @aledj2)

---

*[README.md, line 10 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-LFR_he7CWviIABMB6L0:-LFc523V7eyups1JfpNy:b2zuh1z) ([raw file](https://github.com/moka-guys/dnanexus_nanopore_htt_downsample/blob/9009365e9875f24fc372d5f12a8825b5acb37c73/README.md#L10)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

ok, will hold off on this
</blockquote></details>

OK done now

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1)*

**Comment by aledj2** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_nanopore_htt_downsample/1#-:-LFcDe4S94901dopqq7y:bnfp4nl)*

**Pull request merged**
